name: Pull Request Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  cleanup:
    name: Cleanup Docker images
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Cleanup
        uses: ./.github/actions/clean
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          snapshot_version: pr-${{ github.event.pull_request.number }}
